version: '3.4'

services:
  sqldata:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/data/postgres
    ports:
      - "5432:1433"
    volumes:
      - gtword-sqldata:/data/postgres

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SpaClient=http://${GTWORD_EXTERNAL_DNS_NAME_OR_IP}:5290
      - WebAggClient=http://${GTWORD_EXTERNAL_DNS_NAME_OR_IP}:5205
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "5105:80"

  guessword-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - IdentityUrl=http://${GTWORD_EXTERNAL_DNS_NAME_OR_IP}:5017
      - EventBusConnection=${ESHOP_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${GTWORD_SERVICE_BUS_USERNAME}
      - EventBusPassword=${GTWORD_SERVICE_BUS_PASSWORD}
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - PORT=80
      - PATH_BASE=/guessword-api
    ports:
      - "5282:80"

  guessworddictionary-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=${ESHOP_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${GTWORD_SERVICE_BUS_USERNAME}
      - EventBusPassword=${GTWORD_SERVICE_BUS_PASSWORD}
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - PORT=80
      - PATH_BASE=/guessworddictionary-api
    ports:
      - "5018:80"

  tryguessword-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EventBusUserName=${GTWORD_SERVICE_BUS_USERNAME}
      - EventBusPassword=${GTWORD_SERVICE_BUS_PASSWORD}
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - PORT=80
      - PATH_BASE=/tryguessword-api
    ports:
      - "5003:80"

  webagg:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GuessWordDictionaryUrlHC=http://guessworddictionary-api/hc
      - GuessWordUrlHC=http://guessword-api/hc
      - TryGuessWordUrlHC=http://guessword-api/hc
      - IdentityUrlHC=http://identity-api/hc
      - IdentityUrlExternal=http://${GTWORD_EXTERNAL_DNS_NAME_OR_IP}:5105
    ports:
      - "5205:80"

  webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HealthChecksUI__HealthChecks__0__Name=Web Aggregator GW HTTP Check
      - HealthChecksUI__HealthChecks__0__Uri=http://webagg/hc
      - HealthChecksUI__HealthChecks__1__Name=WebSPA HTTP Check
      - HealthChecksUI__HealthChecks__1__Uri=http://webspa/hc
      - HealthChecksUI__HealthChecks__2__Name=Identity HTTP Check
      - HealthChecksUI__HealthChecks__2__Uri=http://identity-api/hc
      - HealthChecksUI__HealthChecks__3__Name=GuessWord HTTP Check
      - HealthChecksUI__HealthChecks__3__Uri=http://guessword-api/hc
      - HealthChecksUI__HealthChecks__4__Name=GuessWordDictionary HTTP Check
      - HealthChecksUI__HealthChecks__4__Uri=http://guessworddictionary-api/hc
      - HealthChecksUI__HealthChecks__5__Name=TryGuessWord HTTP Check
      - HealthChecksUI__HealthChecks__5__Uri=http://tryguessword-api/hc
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "5107:80"

  webspa:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - IdentityUrl=http://${GTWORD_EXTERNAL_DNS_NAME_OR_IP}:5017
      - IdentityUrlHC=http://identity-api/hc
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "5290:80"

volumes:
  gtword-sqldata:
    external: false
